### PR TITLE
New cheats for DragonFireClient

### PR DESCRIPTION
**Pull request by Code-Sploit**
### Added cheats:

1) JetPack                                               [_Fly into the air when holding jump key_]
2) LessFallDamage                               [_No matter from how high you fall your fall damage is **always** reduced to 0.5 heart_]
3) AutoPunch                                         [_Punch automatically_]
4) HighJump                                          [_Jump 1 block higher then normal_]
5) LessGravity                                       [_Lowers your gravity_]
6) SpeedHack                                       [_Multiplies default movement speed with a factor of 2.0 (Can be **buggy**)_]
7) AutoSprint                                         [_Automatically press the sprint button (Can be usefull in mineclone)_]
8) NoSlip                                               [_Prevents slipping on for example ice_]
9) PlayerESP                                        [_Highlights players_]
10) PlayerTracers                                [_Draw tracers to players_]

### CODE REVIEW

**Comment by LizzyFleckenstein03** [comment]
About LessGravity, HighJump and SpeedHack: There will be a possibility to set_physics_override from CSM, so it makes no sense to hardcode it in C++. AntiSlip should be renamed to NoSlip (like NoSlow). LessFallDamage is useful, so I will merge it for now but later we might consider letting Lua register handlers to (partially) prevent fall damage. JetPack is ok.

**Comment by Code-Sploit** [comment]
I will rename AntiSlip, but the LUA part will have to be your show.
Cause i am a bit of a noob in LUA. But pro in C++, C, Python and Ruby.

**Comment by corarona** [comment]
check this to make jetpack work as expected (i.e. make it work when you're falling) – it's really nice :)
https://repo.or.cz/waspsaliva.git/commitdiff/f1713e3b717c4cbd2c65db341ccf4dfb2ea36118

**Comment by LizzyFleckenstein03** [comment]
I think that ESP and Tracers should highlight only players and there should be EntityTracers and EntityESP

**Comment by Code-Sploit** [comment]
I have now:
Tracers: Traces objects and entitys, NOT players
ESP: Highlights objects and entitys NOT players
PlayerESP: Highlights players
PlayerTracers: Traces players

**Comment by Code-Sploit** [comment]
I will add and delete to final: ESP, Tracers, EntityTracers, EntityESP

**Pull request closed without merging**
